apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest   # ton image locale
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            # -------------------------
            # Database (Postgres)
            # -------------------------
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/authdb
            - name: SPRING_DATASOURCE_USERNAME
              value: authuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver

            # -------------------------
            # OAuth2 / Keycloak
            # -------------------------
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
              value: auth-service-client
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
              value: 6YPC6zNOvt2sENGlD8AGH2vJtnTM7R7R
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: http://keycloak:8080/realms/PFE-Realm
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
              value: http://keycloak:8080/realms/PFE-Realm/protocol/openid-connect/auth
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
              value: http://keycloak:8080/realms/PFE-Realm/protocol/openid-connect/token
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI
              value: http://keycloak:8080/realms/PFE-Realm/protocol/openid-connect/userinfo
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI
              value: http://keycloak:8080/realms/PFE-Realm/protocol/openid-connect/certs
            - name: SPRING_SECURITY_RESOURCESERVER_JWT_ISSUER_URI
              value: http://keycloak:8080/realms/PFE-Realm
            - name: SPRING_SECURITY_RESOURCESERVER_JWT_JWK_SET_URI
              value: http://keycloak:8080/realms/PFE-Realm/protocol/openid-connect/certs

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

