apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-auth
  template:
    metadata:
      labels:
        app: frontend-auth
    spec:
      containers:
      - name: frontend-auth
        image: frontend-auth:latest
        imagePullPolicy: Never  # Utiliser l'image locale (Minikube)
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-auth-service
spec:
  type: NodePort
  selector:
    app: frontend-auth
  ports:
    - port: 80        # Port interne du container
      targetPort: 80  # Mapping vers le containerPort
      nodePort: 30001 # Port accessible depuis la VM/h√¥te
